sudo: required
services:
  - docker

before install:
  - docker build -t georgios/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true  georgios/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-eu-west-1-905161267287"
  bucket_path: "docker"
  on:
   branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

 
